name: build

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build  with cache and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile.dev
          tags: ${{ secrets.DOCKERHUB_TAG }}-dev-cache
          cache-from: type=gha
          cache-to: type=gha, mode=max