name: build

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build AMD64 arch and push
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKERHUB_TAG }}-amd64
      -
        name: Build Arm64 arch and push
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/arm64
          tags: ${{ secrets.DOCKERHUB_TAG }}-arm64
      -
        name: Build ARM/v7 arch and push 
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/arm/v7
          tags: ${{ secrets.DOCKERHUB_TAG }}-arm-v7